### PR TITLE
Various changes and additions

### PR DESCRIPTION
**Pull request by mnmt**

### CODE REVIEW

**Comment by mnmt** [comment]
Fixed command to work with "lastlogouts" since "userinfo" no longer used.

**Comment by mnmt** [comment]
Attempted to change it to what I thought you wanted

**Comment by mnmt** [comment]
Other changes added, !hist now lists in most recent logout order, small changes (some pep8)

**Comment by mnmt** [comment]
........ WLCX!

**Comment by wlcx** [comment]
A merge 5 years late and on a totally disused project? That's right!

**Comment by mnmt** [comment]
wow! I wonder if any of it still works...  My code was not good.

**Pull request merged**
